# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('p', models.FileField(upload_to='pano')),
                ('location', models.CharField(max_length=200)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_title', models.CharField(max_length=200)),
                ('scene_caption', models.CharField(max_length=200)),
                ('s', models.FileField(upload_to='tour')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=200)),
                ('tour_location', models.CharField(max_length=200)),
                ('tour_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tour_uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tour_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tour'),
        ),
    ]
