# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180421_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='tour',
            field=models.IntegerField(),
        ),
    ]
